def get_tbProject_ingestion_query(start_ts, end_ts, start_ts_schedule, end_ts_schedule, reprocess_list):

    if reprocess_list: # Edit
        values_sql = ", ".join(
            str(row[0]) for row in reprocess_list
        )
        is_reprocess_sql = f"""
            (ProjectId IN ({values_sql})) AS is_reprocess -- Edit
        """
    else:
        is_reprocess_sql = """
            FALSE AS is_reprocess
        """
    return f"""
WITH tpj AS ( --Edit
    SELECT
        *,""" + is_reprocess_sql + f""",
        ((
	    CreatedDate >= TIMESTAMP '{start_ts}'
		    AND CreatedDate <  TIMESTAMP '{end_ts}'
		)
		OR
		(
		    UpdatedDate >= TIMESTAMP '{start_ts}'
		    AND UpdatedDate <  TIMESTAMP '{end_ts}'
		)) AS is_date_match_manual,
		((
	    CreatedDate >= TIMESTAMP '{start_ts_schedule}'
		    AND CreatedDate <  TIMESTAMP '{end_ts_schedule}'
		)
		OR
		(
		    UpdatedDate >= TIMESTAMP '{start_ts_schedule}'
		    AND UpdatedDate <  TIMESTAMP '{end_ts_schedule}'
		)) AS is_date_match_schedule,
        COUNT(*) OVER (
            PARTITION BY ProjectId --Edit
        ) AS dup_cnt,
        ROW_NUMBER() OVER (
            PARTITION BY ProjectId --Edit
            ORDER BY
                COALESCE(UpdatedDate, CreatedDate) DESC
        ) AS rn
    FROM tbProject --Edit
),
tbr AS (
    SELECT
        tbrr.ProjectId,
        tbrr.IntegrationAreaText,
        tbrr.ProjectEndDate,
        tbrr.ProjectStartDate,
        ROW_NUMBER() OVER (
            PARTITION BY tbrr.ProjectId
            ORDER BY COALESCE(tbrr.UpdatedDate, tbrr.CreatedDate) DESC
        ) AS rn
    FROM tbBudgetRequest tbrr
),
tpbm AS (
    SELECT
        tpbmr.ProjectId,
        tpbmr.ProjectBuildingMonthlyPaymentId,
        ROW_NUMBER() OVER (
            PARTITION BY tpbmr.ProjectId
            ORDER BY COALESCE(tpbmr.UpdatedDate, tpbmr.CreatedDate) DESC
        ) AS rn
    FROM tbprojectbuildingmonthlypayment tpbmr
),
tpbms AS (
    SELECT
        tpbmsr.ProjectBuildingMonthlyPaymentId,
        tpbmsr.GSCodeDetailId,
        ROW_NUMBER() OVER (
            PARTITION BY tpbmsr.ProjectBuildingMonthlyPaymentId
            ORDER BY COALESCE(tpbmsr.UpdatedDate, tpbmsr.CreatedDate) DESC
        ) AS rn
    FROM tbprojectbuildingmonthlypaymentbysource tpbmsr
)
SELECT
	tpj.ProjectId AS ProjectId,
    tpj.CreatedDate AS CreatedDate,
    tpj.CreatedBy AS CreatedBy,
    tpj.UpdatedDate AS UpdatedDate,
    tpj.UpdatedBy AS UpdatedBy,
    tpj.ProjectCode AS ProjectCode,
    tpj.StartYear AS StartYear,
    tpj.EndYear AS EndYear,
    tpj.IsTracking AS IsTracking,
    tpj.ProjectTransitionId AS ProjectTransitionId,
    tpj.DateTime1 AS DateTime1,
    tpj.DateTime10 AS DateTime10,
    tpj.DateTime2 AS DateTime2,
    tpj.DateTime3 AS DateTime3,
    tpj.DateTime4 AS DateTime4,
    tpj.DateTime5 AS DateTime5,
    tpj.DateTime6 AS DateTime6,
    tpj.DateTime7 AS DateTime7,
    tpj.DateTime8 AS DateTime8,
    tpj.DateTime9 AS DateTime9,
    tpj.WaterTowerAmount AS WaterTowerAmount,
    tpj.NewCapacity AS NewCapacity,
    tpj.Pipelength AS Pipelength,
    tpj.WaterTowerSize AS WaterTowerSize,
    tpj.ActivityTypeId AS ActivityTypeId,
    tpj.CoordinatorEmail AS CoordinatorEmail,
    tpj.CoordinatorName AS CoordinatorName,
    tpj.CoordinatorPosition AS CoordinatorPosition,
    tpj.CoordinatorTel AS CoordinatorTel,
    tpj.ImageId AS ImageId,
    tpj.NeedReason AS NeedReason,
    tpj.PlanDay AS PlanDay,
    tpj.ProjectDurationTypeId AS ProjectDurationTypeId,
    tpj.ProjectName AS ProjectName,
    tpj.ResponsibleAmphoeId AS ResponsibleAmphoeId,
    tpj.ResponsibleEmail AS ResponsibleEmail,
    tpj.ResponsibleName AS ResponsibleName,
    tpj.ResponsiblePosition AS ResponsiblePosition,
    tpj.ResponsibleProvinceId AS ResponsibleProvinceId,
    tpj.ResponsibleTambonId AS ResponsibleTambonId,
    tpj.ResponsibleTel AS ResponsibleTel,
    tpj.ResponsibleUnitText AS ResponsibleUnitText,
    tpj.AddWaterProd AS AddWaterProd,
    tpj.AddWaterUserAmount AS AddWaterUserAmount,
    tpj.AmountOfWaterIncrease AS AmountOfWaterIncrease,
    tpj.AnalyzeBC AS AnalyzeBC,
    tpj.AnalyzeIRR AS AnalyzeIRR,
    tpj.AnalyzeNPV AS AnalyzeNPV,
    tpj.DurableGoodsId AS DurableGoodsId,
    tpj.EndLocation AS EndLocation,
    tpj.ExistPipeRepairAmount AS ExistPipeRepairAmount,
    tpj.ExistPipeSize AS ExistPipeSize,
    tpj.ExistPipeTypeId AS ExistPipeTypeId,
    tpj.ExistPipeWaterLoss AS ExistPipeWaterLoss,
    tpj.ExistPipeYear AS ExistPipeYear,
    tpj.ExistWaterProd AS ExistWaterProd,
    tpj.ExistWaterUserAmount AS ExistWaterUserAmount,
    tpj.GoodsNewAmount AS GoodsNewAmount,
    tpj.GoodsNewPricePerAmount AS GoodsNewPricePerAmount,
    tpj.GoodsNewTotal AS GoodsNewTotal,
    tpj.GoodsNewUnit AS GoodsNewUnit,
    tpj.GoodsReasonItemTypeId AS GoodsReasonItemTypeId,
    tpj.InstallMeterAmount AS InstallMeterAmount,
    tpj.InstallMeterSize AS InstallMeterSize,
    tpj.InstallMeterTypeId AS InstallMeterTypeId,
    tpj.InstallMeterWaterLoss AS InstallMeterWaterLoss,
    tpj.ItNewAmount AS ItNewAmount,
    tpj.ItNewPricePerAmount AS ItNewPricePerAmount,
    tpj.ItNewTotal AS ItNewTotal,
    tpj.ItNewUnit AS ItNewUnit,
    tpj.ItReasonItemTypeId AS ItReasonItemTypeId,
    tpj.LandAmount AS LandAmount,
    tpj.LandEnterYear AS LandEnterYear,
    tpj.LandPriceCompany AS LandPriceCompany,
    tpj.LandPriceCurrent AS LandPriceCurrent,
    tpj.LandPriceUnit AS LandPriceUnit,
    tpj.LandReason AS LandReason,
    tpj.LandRequestBudget AS LandRequestBudget,
    tpj.LandRequestBudgetPerItem AS LandRequestBudgetPerItem,
    tpj.NewPipeLength AS NewPipeLength,
    tpj.NewPipeSize AS NewPipeSize,
    tpj.NewPipeTypeId AS NewPipeTypeId,
    tpj.NewPipeWaterLoss AS NewPipeWaterLoss,
    tpj.OperationAreaText AS OperationAreaText,
    tpj.Polygon AS Polygon,
    tpj.PowerReserve AS PowerReserve,
    tpj.PowerReserveContentSummary AS PowerReserveContentSummary,
    tpj.PowerReserveEffect AS PowerReserveEffect,
    tpj.PowerReserveInstallDateTime AS PowerReserveInstallDateTime,
    tpj.PowerReserveNumber AS PowerReserveNumber,
    tpj.PowerReserveReason AS PowerReserveReason,
    tpj.PowerReserveResultOutcome AS PowerReserveResultOutcome,
    tpj.PriceReserveGoods AS PriceReserveGoods,
    tpj.ReserveOfUrgent AS ReserveOfUrgent,
    tpj.ReserveOfUrgentContentSummary AS ReserveOfUrgentContentSummary,
    tpj.ReserveOfUrgentDrought AS ReserveOfUrgentDrought,
    tpj.ReserveOfUrgentEffect AS ReserveOfUrgentEffect,
    tpj.ReserveOfUrgentNumber AS ReserveOfUrgentNumber,
    tpj.ReserveOfUrgentPipe AS ReserveOfUrgentPipe,
    tpj.ReserveOfUrgentPipelength AS ReserveOfUrgentPipelength,
    tpj.ReserveOfUrgentReason AS ReserveOfUrgentReason,
    tpj.ReserveOfUrgentResultOutcome AS ReserveOfUrgentResultOutcome,
    tpj.ReserveOfUrgentTypeId AS ReserveOfUrgentTypeId,
    tpj.RoiPipeDiameter AS RoiPipeDiameter,
    tpj.RoiPipeLength AS RoiPipeLength,
    tpj.RoiPipeTotalLength AS RoiPipeTotalLength,
    tpj.RoiPipeType AS RoiPipeType,
    tpj.StartLocation AS StartLocation,
    tpj.WaterOther AS WaterOther,
    tpj.waterProblem AS waterProblem,
    tpj.waterProblemConform AS waterProblemConform,
    tpj.waterProjectDetail AS waterProjectDetail,
    tpj.RequesterUnit AS RequesterUnit,
    tpj.OperationBudgetAmount AS OperationBudgetAmount,
    tpj.InvestWbsId AS InvestWbsId,
    tpj.PriceReserve AS PriceReserve,
    tpj.TrusteeUnitId AS TrusteeUnitId,
    tpj.HasProjectLimit1M1 AS HasProjectLimit1M1,
    tpj.HasProjectLimit1M2 AS HasProjectLimit1M2,
    tpj.Location AS Location,
    tpj.NewLandDate AS NewLandDate,
    tpj.NewLandTypeId AS NewLandTypeId,
    tpj.ProjectBoq1Date AS ProjectBoq1Date,
    tpj.ProjectBoq2Date AS ProjectBoq2Date,
    tpj.ProjectBoqTypeId AS ProjectBoqTypeId,
    tpj.ProjectFormat1Date AS ProjectFormat1Date,
    tpj.ProjectFormat2Date AS ProjectFormat2Date,
    tpj.ProjectFormatTypeId AS ProjectFormatTypeId,
    tpj.ProjectJobAsset AS ProjectJobAsset,
    tpj.ProjectJobTypeId AS ProjectJobTypeId,
    tpj.ProjectLimit1M1Date AS ProjectLimit1M1Date,
    tpj.ProjectLimit1M2Date AS ProjectLimit1M2Date,
    tpj.ProjectTor1Date AS ProjectTor1Date,
    tpj.ProjectTor2Date AS ProjectTor2Date,
    tpj.ProjectTorTypeId AS ProjectTorTypeId,
    tpj.ProjectWater1Date AS ProjectWater1Date,
    tpj.ProjectWater2Date AS ProjectWater2Date,
    tpj.ProjectWaterTypeId AS ProjectWaterTypeId,
    tpj.UseLandDate AS UseLandDate,
    tpj.UseLandTypeId AS UseLandTypeId,
    tpj.hasExistLand AS hasExistLand,
    tpj.hasNewLand AS hasNewLand,
    tpj.hasUseLand AS hasUseLand,
    tpj.ApproveDate AS ApproveDate,
    tpj.AssessmentPercent AS AssessmentPercent,
    tpj.ContractCreateDate AS ContractCreateDate,
    tpj.DesignPercent AS DesignPercent,
    tpj.DocumentPercent AS DocumentPercent,
    tpj.MidPrice_ExcludeVat AS MidPrice_ExcludeVat,
    tpj.MidPrice_IncludedVat AS MidPrice_IncludedVat,
    tpj.OfferDate AS OfferDate,
    tpj.PostDate AS PostDate,
    tpj.PostNumber AS PostNumber,
    tpj.PriceApprove_ExcludeVat AS PriceApprove_ExcludeVat,
    tpj.PriceApprove_IncludedVat AS PriceApprove_IncludedVat,
    tpj.PriceContract_ExcludeVat AS PriceContract_ExcludeVat,
    tpj.PriceContract_IncludedVat AS PriceContract_IncludedVat,
    tpj.PriceCreateDate AS PriceCreateDate,
    tpj.PriceOffer_ExcludeVat AS PriceOffer_ExcludeVat,
    tpj.PriceOffer_IncludedVat AS PriceOffer_IncludedVat,
    tpj.PriceSendDate AS PriceSendDate,
    tpj.PublishDate AS PublishDate,
    tpj.ReceivedDate AS ReceivedDate,
    tpj.SurveyPercent AS SurveyPercent,
    tpj.TORCreateDate AS TORCreateDate,
    tpj.TOREndDate AS TOREndDate,
    tpj.TORSendDate AS TORSendDate,
    tpj.TORStartDate AS TORStartDate,
    tpj.VerifyPercent AS VerifyPercent,
    tpj.EndDateConstruction AS EndDateConstruction,
    tpj.InspectionDate AS InspectionDate,
    tpj.StartDateConstruction AS StartDateConstruction,
    tpj.UpdatedByConstruction AS UpdatedByConstruction,
    tpj.UpdatedByPurchase AS UpdatedByPurchase,
    tpj.UpdatedBySurvey AS UpdatedBySurvey,
    tpj.UpdatedDateConstruction AS UpdatedDateConstruction,
    tpj.UpdatedDatePurchase AS UpdatedDatePurchase,
    tpj.UpdatedDateSurvey AS UpdatedDateSurvey,
    tpj.Committee AS Committee,
    tpj.IsFinish AS IsFinish,
    tpj.Reason AS Reason,
    tpj.Supervisor AS Supervisor,
    tpj.PlanSuccess AS PlanSuccess,
    tpj.Problems AS Problems,
    tpj.ProgressReportStatusId AS ProgressReportStatusId,
    tpj.ProgressReportStepId AS ProgressReportStepId,
    tpj.ProgressReportSummaryStatusId AS ProgressReportSummaryStatusId,
    tpj.ProjectEndDate AS ProjectEndDate,
    tpj.ProjectStartDate AS ProjectStartDate,
    tpj.RealSuccess AS RealSuccess,
    tpj.ResponsibleUnitId AS ResponsibleUnitId,
    tpj.InvestBudgetAmount AS InvestBudgetAmount,
    tpj.WholeInvestBudgetRequested AS WholeInvestBudgetRequested,
    tpj.PumpAmount AS PumpAmount,
    tpj.SupplyStationAmount AS SupplyStationAmount,
    tpj.WaterTankAmount AS WaterTankAmount,
    tpj.WaterTankSize AS WaterTankSize,
    tpj.River AS River,
    tpj.Solution AS Solution,
    tpj.UpdatedBySuccess AS UpdatedBySuccess,
    tpj.UpdatedDateSuccess AS UpdatedDateSuccess,
    tpj.NewLandWaitDate AS NewLandWaitDate,
    tpj.ProjectPipe1Date AS ProjectPipe1Date,
    tpj.ProjectPipe2Date AS ProjectPipe2Date,
    tpj.ProjectPipeTypeId AS ProjectPipeTypeId,
    tpj.UseLandWaitDate AS UseLandWaitDate,
    tpj.ConstructionSupervisorUnitId AS ConstructionSupervisorUnitId,
    tpj.DesignSupervisorUnitId AS DesignSupervisorUnitId,
    tpj.ProcurementSupervisorUnitId AS ProcurementSupervisorUnitId,
    tpj.IntegrationPlanId AS IntegrationPlanId,
    tpj.ProgressReportIssueTypeGroupId AS ProgressReportIssueTypeGroupId,
    tpj.ProgressReportIssueTypeId AS ProgressReportIssueTypeId,
    tpj.EntityStatusId AS EntityStatusId,
    tpj.TreasuryAmountDetail AS TreasuryAmountDetail,
    tpj.LandAmountField AS LandAmountField,
    tpj.LandAmountMeter AS LandAmountMeter,
    tpj.LandAmountWa AS LandAmountWa,
    tpj.LandAmountWork AS LandAmountWork,
    tpj.LeasingTypeId AS LeasingTypeId,
    tpj.ActivityTypeCustomId AS ActivityTypeCustomId,
    tpj.CostCenterId AS CostCenterId,
    tpj.ProcurementTypeId AS ProcurementTypeId,
    tpj.HaveBudgetRequest AS HaveBudgetRequest,
    tpj.SapUnitId AS SapUnitId,
    tbr.ProjectId AS tbBudgetRequest_ProjectId,
    tbr.IntegrationAreaText AS tbBudgetRequest_IntegrationAreaText,
    tbr.ProjectEndDate AS tbBudgetRequest_ProjectEndDate,
    tbr.ProjectStartDate AS tbBudgetRequest_ProjectStartDate,
    tmpg.ProgressReportStatusId AS tbmProgressReportStatus_ProgressReportStatusId,
	tmpg.Name AS tbmProgressReportStatus_Name,
    tpbm.ProjectId AS tbProjectBuildingMonthlyPmt_ProjectId,
    tpbm.ProjectBuildingMonthlyPaymentId AS tbProjectBuildingMonthlyPmt_ProjectBuildingMonthlyPaymentId,
    tpbms.ProjectBuildingMonthlyPaymentId AS tbProjectBuildingMonthlyPmtBS_ProjectBuildingMonthlyPaymentId,
    tpbms.GSCodeDetailId AS tbProjectBuildingMonthlyPmtBS_GSCodeDetailId,
    tgscd.GSCodeDetailId AS tbGsCodeDetail_GSCodeDetailId,
    tgscd.Amount AS tbGsCodeDetail_Amount,
    ----------------------------------------------------------
    CASE
        WHEN dup_cnt > 1 THEN dup_cnt
        ELSE 0
    END AS DuplicatedCount,
    CASE 
		WHEN is_date_match_manual then 'DM'
		WHEN is_reprocess and not is_date_match_manual then 'RE'
		else 'NA'
	END as RecordStatus
FROM tpj
LEFT JOIN tbmprogressreportstatus tmpg ON (tpj.ProgressReportStatusId = tmpg.ProgressReportStatusId )
LEFT JOIN tbr ON (tpj.ProjectId = tbr.ProjectId AND tbr.rn = 1)
LEFT JOIN tpbm ON (tpj.ProjectId = tpbm.ProjectId AND tpbm.rn = 1)
LEFT JOIN tpbms ON (tpbm.ProjectBuildingMonthlyPaymentId = tpbms.ProjectBuildingMonthlyPaymentId AND tpbms.rn = 1)
LEFT JOIN tbgscodedetail tgscd ON (tpbms.GSCodeDetailId = tgscd.GSCodeDetailId )
WHERE tpj.rn = 1
AND (tpj.is_reprocess OR tpj.is_date_match_manual OR tpj.is_date_match_schedule) -- Edit
"""

def get_tbProject_staging_schema():
    return [
        {'name': 'ProjectId', 'type': 'INT'},
        {'name': 'CreatedDate', 'type': 'TIMESTAMP'},
        {'name': 'CreatedBy', 'type': 'STRING'},
        {'name': 'UpdatedDate', 'type': 'TIMESTAMP'},
        {'name': 'UpdatedBy', 'type': 'STRING'},
        {'name': 'ProjectCode', 'type': 'STRING'},
        {'name': 'StartYear', 'type': 'INT'},
        {'name': 'EndYear', 'type': 'INT'},
        {'name': 'IsTracking', 'type': 'BOOLEAN'},
        {'name': 'ProjectTransitionId', 'type': 'INT'},
        {'name': 'DateTime1', 'type': 'TIMESTAMP'},
        {'name': 'DateTime10', 'type': 'TIMESTAMP'},
        {'name': 'DateTime2', 'type': 'TIMESTAMP'},
        {'name': 'DateTime3', 'type': 'TIMESTAMP'},
        {'name': 'DateTime4', 'type': 'TIMESTAMP'},
        {'name': 'DateTime5', 'type': 'TIMESTAMP'},
        {'name': 'DateTime6', 'type': 'TIMESTAMP'},
        {'name': 'DateTime7', 'type': 'TIMESTAMP'},
        {'name': 'DateTime8', 'type': 'TIMESTAMP'},
        {'name': 'DateTime9', 'type': 'TIMESTAMP'},
        {'name': 'WaterTowerAmount', 'type': 'FLOAT'},
        {'name': 'NewCapacity', 'type': 'FLOAT'},
        {'name': 'Pipelength', 'type': 'FLOAT'},
        {'name': 'WaterTowerSize', 'type': 'FLOAT'},
        {'name': 'ActivityTypeId', 'type': 'INT'},
        {'name': 'CoordinatorEmail', 'type': 'STRING'},
        {'name': 'CoordinatorName', 'type': 'STRING'},
        {'name': 'CoordinatorPosition', 'type': 'STRING'},
        {'name': 'CoordinatorTel', 'type': 'STRING'},
        {'name': 'ImageId', 'type': 'INT'},
        {'name': 'NeedReason', 'type': 'STRING'},
        {'name': 'PlanDay', 'type': 'INT'},
        {'name': 'ProjectDurationTypeId', 'type': 'INT'},
        {'name': 'ProjectName', 'type': 'STRING'},
        {'name': 'ResponsibleAmphoeId', 'type': 'INT'},
        {'name': 'ResponsibleEmail', 'type': 'STRING'},
        {'name': 'ResponsibleName', 'type': 'STRING'},
        {'name': 'ResponsiblePosition', 'type': 'STRING'},
        {'name': 'ResponsibleProvinceId', 'type': 'INT'},
        {'name': 'ResponsibleTambonId', 'type': 'INT'},
        {'name': 'ResponsibleTel', 'type': 'STRING'},
        {'name': 'ResponsibleUnitText', 'type': 'STRING'},
        {'name': 'AddWaterProd', 'type': 'FLOAT'},
        {'name': 'AddWaterUserAmount', 'type': 'INT'},
        {'name': 'AmountOfWaterIncrease', 'type': 'STRING'},
        {'name': 'AnalyzeBC', 'type': 'FLOAT'},
        {'name': 'AnalyzeIRR', 'type': 'FLOAT'},
        {'name': 'AnalyzeNPV', 'type': 'FLOAT'},
        {'name': 'DurableGoodsId', 'type': 'INT'},
        {'name': 'EndLocation', 'type': 'STRING'},
        {'name': 'ExistPipeRepairAmount', 'type': 'INT'},
        {'name': 'ExistPipeSize', 'type': 'FLOAT'},
        {'name': 'ExistPipeTypeId', 'type': 'INT'},
        {'name': 'ExistPipeWaterLoss', 'type': 'FLOAT'},
        {'name': 'ExistPipeYear', 'type': 'INT'},
        {'name': 'ExistWaterProd', 'type': 'FLOAT'},
        {'name': 'ExistWaterUserAmount', 'type': 'INT'},
        {'name': 'GoodsNewAmount', 'type': 'INT'},
        {'name': 'GoodsNewPricePerAmount', 'type': 'FLOAT'},
        {'name': 'GoodsNewTotal', 'type': 'FLOAT'},
        {'name': 'GoodsNewUnit', 'type': 'STRING'},
        {'name': 'GoodsReasonItemTypeId', 'type': 'INT'},
        {'name': 'InstallMeterAmount', 'type': 'INT'},
        {'name': 'InstallMeterSize', 'type': 'INT'},
        {'name': 'InstallMeterTypeId', 'type': 'INT'},
        {'name': 'InstallMeterWaterLoss', 'type': 'FLOAT'},
        {'name': 'ItNewAmount', 'type': 'INT'},
        {'name': 'ItNewPricePerAmount', 'type': 'FLOAT'},
        {'name': 'ItNewTotal', 'type': 'FLOAT'},
        {'name': 'ItNewUnit', 'type': 'STRING'},
        {'name': 'ItReasonItemTypeId', 'type': 'INT'},
        {'name': 'LandAmount', 'type': 'FLOAT'},
        {'name': 'LandEnterYear', 'type': 'INT'},
        {'name': 'LandPriceCompany', 'type': 'FLOAT'},
        {'name': 'LandPriceCurrent', 'type': 'FLOAT'},
        {'name': 'LandPriceUnit', 'type': 'FLOAT'},
        {'name': 'LandReason', 'type': 'STRING'},
        {'name': 'LandRequestBudget', 'type': 'FLOAT'},
        {'name': 'LandRequestBudgetPerItem', 'type': 'FLOAT'},
        {'name': 'NewPipeLength', 'type': 'FLOAT'},
        {'name': 'NewPipeSize', 'type': 'FLOAT'},
        {'name': 'NewPipeTypeId', 'type': 'INT'},
        {'name': 'NewPipeWaterLoss', 'type': 'FLOAT'},
        {'name': 'OperationAreaText', 'type': 'STRING'},
        {'name': 'Polygon', 'type': 'STRING'},
        {'name': 'PowerReserve', 'type': 'FLOAT'},
        {'name': 'PowerReserveContentSummary', 'type': 'STRING'},
        {'name': 'PowerReserveEffect', 'type': 'STRING'},
        {'name': 'PowerReserveInstallDateTime', 'type': 'TIMESTAMP'},
        {'name': 'PowerReserveNumber', 'type': 'STRING'},
        {'name': 'PowerReserveReason', 'type': 'STRING'},
        {'name': 'PowerReserveResultOutcome', 'type': 'STRING'},
        {'name': 'PriceReserveGoods', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgent', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentContentSummary', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentDrought', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentEffect', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentNumber', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentPipe', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentPipelength', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentReason', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentResultOutcome', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentTypeId', 'type': 'INT'},
        {'name': 'RoiPipeDiameter', 'type': 'FLOAT'},
        {'name': 'RoiPipeLength', 'type': 'FLOAT'},
        {'name': 'RoiPipeTotalLength', 'type': 'FLOAT'},
        {'name': 'RoiPipeType', 'type': 'STRING'},
        {'name': 'StartLocation', 'type': 'STRING'},
        {'name': 'WaterOther', 'type': 'STRING'},
        {'name': 'waterProblem', 'type': 'STRING'},
        {'name': 'waterProblemConform', 'type': 'BOOLEAN'},
        {'name': 'waterProjectDetail', 'type': 'STRING'},
        {'name': 'RequesterUnit', 'type': 'INT'},
        {'name': 'OperationBudgetAmount', 'type': 'FLOAT'},
        {'name': 'InvestWbsId', 'type': 'INT'},
        {'name': 'PriceReserve', 'type': 'FLOAT'},
        {'name': 'TrusteeUnitId', 'type': 'INT'},
        {'name': 'HasProjectLimit1M1', 'type': 'BOOLEAN'},
        {'name': 'HasProjectLimit1M2', 'type': 'BOOLEAN'},
        {'name': 'Location', 'type': 'STRING'},
        {'name': 'NewLandDate', 'type': 'TIMESTAMP'},
        {'name': 'NewLandTypeId', 'type': 'INT'},
        {'name': 'ProjectBoq1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectBoq2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectBoqTypeId', 'type': 'INT'},
        {'name': 'ProjectFormat1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectFormat2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectFormatTypeId', 'type': 'INT'},
        {'name': 'ProjectJobAsset', 'type': 'STRING'},
        {'name': 'ProjectJobTypeId', 'type': 'INT'},
        {'name': 'ProjectLimit1M1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectLimit1M2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTor1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTor2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTorTypeId', 'type': 'INT'},
        {'name': 'ProjectWater1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectWater2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectWaterTypeId', 'type': 'INT'},
        {'name': 'UseLandDate', 'type': 'TIMESTAMP'},
        {'name': 'UseLandTypeId', 'type': 'INT'},
        {'name': 'hasExistLand', 'type': 'BOOLEAN'},
        {'name': 'hasNewLand', 'type': 'BOOLEAN'},
        {'name': 'hasUseLand', 'type': 'BOOLEAN'},
        {'name': 'ApproveDate', 'type': 'TIMESTAMP'},
        {'name': 'AssessmentPercent', 'type': 'FLOAT'},
        {'name': 'ContractCreateDate', 'type': 'TIMESTAMP'},
        {'name': 'DesignPercent', 'type': 'FLOAT'},
        {'name': 'DocumentPercent', 'type': 'FLOAT'},
        {'name': 'MidPrice_ExcludeVat', 'type': 'FLOAT'},
        {'name': 'MidPrice_IncludedVat', 'type': 'FLOAT'},
        {'name': 'OfferDate', 'type': 'TIMESTAMP'},
        {'name': 'PostDate', 'type': 'TIMESTAMP'},
        {'name': 'PostNumber', 'type': 'FLOAT'},
        {'name': 'PriceApprove_ExcludeVat', 'type': 'FLOAT'},
        {'name': 'PriceApprove_IncludedVat', 'type': 'FLOAT'},
        {'name': 'PriceContract_ExcludeVat', 'type': 'FLOAT'},
        {'name': 'PriceContract_IncludedVat', 'type': 'FLOAT'},
        {'name': 'PriceCreateDate', 'type': 'TIMESTAMP'},
        {'name': 'PriceOffer_ExcludeVat', 'type': 'FLOAT'},
        {'name': 'PriceOffer_IncludedVat', 'type': 'FLOAT'},
        {'name': 'PriceSendDate', 'type': 'TIMESTAMP'},
        {'name': 'PublishDate', 'type': 'TIMESTAMP'},
        {'name': 'ReceivedDate', 'type': 'TIMESTAMP'},
        {'name': 'SurveyPercent', 'type': 'FLOAT'},
        {'name': 'TORCreateDate', 'type': 'TIMESTAMP'},
        {'name': 'TOREndDate', 'type': 'TIMESTAMP'},
        {'name': 'TORSendDate', 'type': 'TIMESTAMP'},
        {'name': 'TORStartDate', 'type': 'TIMESTAMP'},
        {'name': 'VerifyPercent', 'type': 'FLOAT'},
        {'name': 'EndDateConstruction', 'type': 'TIMESTAMP'},
        {'name': 'InspectionDate', 'type': 'TIMESTAMP'},
        {'name': 'StartDateConstruction', 'type': 'TIMESTAMP'},
        {'name': 'UpdatedByConstruction', 'type': 'STRING'},
        {'name': 'UpdatedByPurchase', 'type': 'STRING'},
        {'name': 'UpdatedBySurvey', 'type': 'STRING'},
        {'name': 'UpdatedDateConstruction', 'type': 'TIMESTAMP'},
        {'name': 'UpdatedDatePurchase', 'type': 'TIMESTAMP'},
        {'name': 'UpdatedDateSurvey', 'type': 'TIMESTAMP'},
        {'name': 'Committee', 'type': 'STRING'},
        {'name': 'IsFinish', 'type': 'BOOLEAN'},
        {'name': 'Reason', 'type': 'STRING'},
        {'name': 'Supervisor', 'type': 'STRING'},
        {'name': 'PlanSuccess', 'type': 'FLOAT'},
        {'name': 'Problems', 'type': 'STRING'},
        {'name': 'ProgressReportStatusId', 'type': 'INT'},
        {'name': 'ProgressReportStepId', 'type': 'INT'},
        {'name': 'ProgressReportSummaryStatusId', 'type': 'INT'},
        {'name': 'ProjectEndDate', 'type': 'TIMESTAMP'},
        {'name': 'ProjectStartDate', 'type': 'TIMESTAMP'},
        {'name': 'RealSuccess', 'type': 'FLOAT'},
        {'name': 'ResponsibleUnitId', 'type': 'INT'},
        {'name': 'InvestBudgetAmount', 'type': 'FLOAT'},
        {'name': 'WholeInvestBudgetRequested', 'type': 'FLOAT'},
        {'name': 'PumpAmount', 'type': 'FLOAT'},
        {'name': 'SupplyStationAmount', 'type': 'FLOAT'},
        {'name': 'WaterTankAmount', 'type': 'FLOAT'},
        {'name': 'WaterTankSize', 'type': 'FLOAT'},
        {'name': 'River', 'type': 'STRING'},
        {'name': 'Solution', 'type': 'STRING'},
        {'name': 'UpdatedBySuccess', 'type': 'STRING'},
        {'name': 'UpdatedDateSuccess', 'type': 'TIMESTAMP'},
        {'name': 'NewLandWaitDate', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipe1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipe2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipeTypeId', 'type': 'INT'},
        {'name': 'UseLandWaitDate', 'type': 'TIMESTAMP'},
        {'name': 'ConstructionSupervisorUnitId', 'type': 'INT'},
        {'name': 'DesignSupervisorUnitId', 'type': 'INT'},
        {'name': 'ProcurementSupervisorUnitId', 'type': 'INT'},
        {'name': 'IntegrationPlanId', 'type': 'INT'},
        {'name': 'ProgressReportIssueTypeGroupId', 'type': 'INT'},
        {'name': 'ProgressReportIssueTypeId', 'type': 'INT'},
        {'name': 'EntityStatusId', 'type': 'INT'},
        {'name': 'TreasuryAmountDetail', 'type': 'STRING'},
        {'name': 'LandAmountField', 'type': 'FLOAT'},
        {'name': 'LandAmountMeter', 'type': 'FLOAT'},
        {'name': 'LandAmountWa', 'type': 'FLOAT'},
        {'name': 'LandAmountWork', 'type': 'FLOAT'},
        {'name': 'LeasingTypeId', 'type': 'INT'},
        {'name': 'ActivityTypeCustomId', 'type': 'INT'},
        {'name': 'CostCenterId', 'type': 'INT'},
        {'name': 'ProcurementTypeId', 'type': 'INT'},
        {'name': 'HaveBudgetRequest', 'type': 'INT'},
        {'name': 'SapUnitId', 'type': 'INT'},
        {'name': 'tbBudgetRequest_ProjectId', 'type': 'INT'},
        {'name': 'tbBudgetRequest_IntegrationAreaText', 'type': 'STRING'},
        {'name': 'tbBudgetRequest_ProjectEndDate', 'type': 'TIMESTAMP'},
        {'name': 'tbBudgetRequest_ProjectStartDate', 'type': 'TIMESTAMP'},
        {'name': 'tbmProgressReportStatus_ProgressReportStatusId', 'type': 'INT'},
        {'name': 'tbmProgressReportStatus_Name', 'type': 'STRING'},
        {'name': 'tbProjectBuildingMonthlyPmt_ProjectId', 'type': 'INT'},
        {'name': 'tbProjectBuildingMonthlyPmt_ProjectBuildingMonthlyPaymentId', 'type': 'INT'},
        {'name': 'tbProjectBuildingMonthlyPmtBS_ProjectBuildingMonthlyPaymentId', 'type': 'INT'},
        {'name': 'tbProjectBuildingMonthlyPmtBS_GSCodeDetailId', 'type': 'INT'},
        {'name': 'tbGSCodeDetail_GSCodeDetailId', 'type': 'INT'},
        {'name': 'tbGSCodeDetail_Amount', 'type': 'FLOAT'},
        {'name': 'RecordStatus', 'type': 'STRING'},
        {'name': 'DuplicatedCount', 'type': 'INT'},
    ]
    

def get_tbBudgetRequest_ingestion_query(start_ts, end_ts, start_ts_schedule, end_ts_schedule, reprocess_list):
    
    # if reprocess_list:
        # values_sql = ", ".join(
        #     f"({bid}, {pid})" for bid, pid in reprocess_list
        # )
        # is_reprocess_sql = f"""
        #     ((BudgetRequestId, ProjectId) IN ({values_sql})) AS is_reprocess
        # """
    if reprocess_list:
        values_sql = ", ".join(
            str(row[0]) for row in reprocess_list
        )
        is_reprocess_sql = f"""
            (BudgetRequestId IN ({values_sql})) AS is_reprocess
        """
    else:
        is_reprocess_sql = """
            FALSE AS is_reprocess
        """
    return f"""
WITH tbr AS ( --Edit
    SELECT
        *,""" + is_reprocess_sql + f""",
        ((
	    CreatedDate >= TIMESTAMP '{start_ts}'
		    AND CreatedDate <  TIMESTAMP '{end_ts}'
		)
		OR
		(
		    UpdatedDate >= TIMESTAMP '{start_ts}'
		    AND UpdatedDate <  TIMESTAMP '{end_ts}'
		)) AS is_date_match_manual,
		((
	    CreatedDate >= TIMESTAMP '{start_ts_schedule}'
		    AND CreatedDate <  TIMESTAMP '{end_ts_schedule}'
		)
		OR
		(
		    UpdatedDate >= TIMESTAMP '{start_ts_schedule}'
		    AND UpdatedDate <  TIMESTAMP '{end_ts_schedule}'
		)) AS is_date_match_schedule,
        COUNT(*) OVER (
            PARTITION BY BudgetRequestId --Edit
        ) AS dup_cnt,
        ROW_NUMBER() OVER (
            PARTITION BY BudgetRequestId --Edit
            ORDER BY
                COALESCE(UpdatedDate, CreatedDate) DESC
        ) AS rn
    FROM tbBudgetRequest --Edit
),
tpj AS ( -- Edit
    SELECT
        ProjectId, -- Edit
        ROW_NUMBER() OVER (
            PARTITION BY ProjectId  -- Edit
            ORDER BY COALESCE(UpdatedDate, CreatedDate) DESC
        ) AS rn
    FROM tbProject -- Edit
)
SELECT 
    --------------------- Major Edit -----------------------
	tbr.BudgetRequestId AS BudgetRequestId,
    tbr.CreatedDate AS CreatedDate,
    tbr.CreatedBy AS CreatedBy,
    tbr.UpdatedDate AS UpdatedDate,
    tbr.UpdatedBy AS UpdatedBy,
    tbr.BudgetYearNo AS BudgetYearNo,
    tbr.BudgetRequested AS BudgetRequested,
    tbr.RequesterUnit AS RequesterUnit,
    tbr.Position AS Position,
    tbr.BudgetRequestYearlyTypeId AS BudgetRequestYearlyTypeId,
    tbr.EntityStatusId AS EntityStatusId,
    tbr.BeginPeriodCustomerAmount AS BeginPeriodCustomerAmount,
    tbr.IncreaseCustomerAmount AS IncreaseCustomerAmount,
    tbr.DecreaseCustomerAmount AS DecreaseCustomerAmount,
    tbr.WaterSoldQty AS WaterSoldQty,
    tbr.WaterProducedQty AS WaterProducedQty,
    tbr.WaterProductionQty AS WaterProductionQty,
    tbr.ImageId AS ImageId,
    tbr.ApprovedDate AS ApprovedDate,
    tbr.ApprovedUserId AS ApprovedUserId,
    tbr.ApprovedBudgetAmount AS ApprovedBudgetAmount,
    tbr.RequestId AS RequestId,
    tbr.AllocatedBudgetAmount AS AllocatedBudgetAmount,
    tbr.BudgetRequestNumber AS BudgetRequestNumber,
    tbr.TrusteeUnitId AS TrusteeUnitId,
    tbr.ActivityTypeId AS ActivityTypeId,
    tbr.AddWaterProd AS AddWaterProd,
    tbr.AddWaterUserAmount AS AddWaterUserAmount,
    tbr.AmountOfWaterIncrease AS AmountOfWaterIncrease,
    tbr.AnalyzeBC AS AnalyzeBC,
    tbr.AnalyzeIRR AS AnalyzeIRR,
    tbr.AnalyzeNPV AS AnalyzeNPV,
    tbr.CoordinatorEmail AS CoordinatorEmail,
    tbr.CoordinatorName AS CoordinatorName,
    tbr.CoordinatorPosition AS CoordinatorPosition,
    tbr.CoordinatorTel AS CoordinatorTel,
    tbr.Discriminator AS Discriminator,
    tbr.DurableGoodsId AS DurableGoodsId,
    tbr.EndLocation AS EndLocation,
    tbr.EndPaymentYear AS EndPaymentYear,
    tbr.ExistPipeRepairAmount AS ExistPipeRepairAmount,
    tbr.ExistPipeSize AS ExistPipeSize,
    tbr.ExistPipeTypeId AS ExistPipeTypeId,
    tbr.ExistPipeWaterLoss AS ExistPipeWaterLoss,
    tbr.ExistPipeYear AS ExistPipeYear,
    tbr.ExistWaterProd AS ExistWaterProd,
    tbr.ExistWaterUserAmount AS ExistWaterUserAmount,
    tbr.GoodsNewAmount AS GoodsNewAmount,
    tbr.GoodsNewPricePerAmount AS GoodsNewPricePerAmount,
    tbr.GoodsNewTotal AS GoodsNewTotal,
    tbr.GoodsNewUnit AS GoodsNewUnit,
    tbr.GoodsReasonItemTypeId AS GoodsReasonItemTypeId,
    tbr.HasProjectLimit1M1 AS HasProjectLimit1M1,
    tbr.HasProjectLimit1M2 AS HasProjectLimit1M2,
    tbr.InstallMeterAmount AS InstallMeterAmount,
    tbr.InstallMeterSize AS InstallMeterSize,
    tbr.InstallMeterTypeId AS InstallMeterTypeId,
    tbr.InstallMeterWaterLoss AS InstallMeterWaterLoss,
    tbr.IntegrationAmphoeId AS IntegrationAmphoeId,
    tbr.IntegrationAreaText AS IntegrationAreaText,
    tbr.IntegrationBenefit AS IntegrationBenefit,
    tbr.IntegrationCoordinatorEmail AS IntegrationCoordinatorEmail,
    tbr.IntegrationCoordinatorName AS IntegrationCoordinatorName,
    tbr.IntegrationCoordinatorPosition AS IntegrationCoordinatorPosition,
    tbr.IntegrationCoordinatorTel AS IntegrationCoordinatorTel,
    tbr.IntegrationEvaDuration AS IntegrationEvaDuration,
    tbr.IntegrationEvaEquipment AS IntegrationEvaEquipment,
    tbr.IntegrationEvaImplement AS IntegrationEvaImplement,
    tbr.IntegrationGuideline AS IntegrationGuideline,
    tbr.IntegrationIndicator AS IntegrationIndicator,
    tbr.IntegrationIsPresident AS IntegrationIsPresident,
    tbr.IntegrationIsResolution AS IntegrationIsResolution,
    tbr.IntegrationIsStatusOther AS IntegrationIsStatusOther,
    tbr.IntegrationIsUnderProvince AS IntegrationIsUnderProvince,
    tbr.IntegrationObjective AS IntegrationObjective,
    tbr.IntegrationOperation AS IntegrationOperation,
    tbr.IntegrationOutput AS IntegrationOutput,
    tbr.IntegrationPlanId AS IntegrationPlanId,
    tbr.IntegrationPolicy AS IntegrationPolicy,
    tbr.IntegrationPosition AS IntegrationPosition,
    tbr.IntegrationPresidentDate AS IntegrationPresidentDate,
    tbr.IntegrationProjectTypeId AS IntegrationProjectTypeId,
    tbr.IntegrationProvinceId AS IntegrationProvinceId,
    tbr.IntegrationQualitative AS IntegrationQualitative,
    tbr.IntegrationQuantitative AS IntegrationQuantitative,
    tbr.IntegrationReason AS IntegrationReason,
    tbr.IntegrationRef AS IntegrationRef,
    tbr.IntegrationResolutionDate AS IntegrationResolutionDate,
    tbr.IntegrationResponsibleEmail AS IntegrationResponsibleEmail,
    tbr.IntegrationResponsibleName AS IntegrationResponsibleName,
    tbr.IntegrationResponsiblePosition AS IntegrationResponsiblePosition,
    tbr.IntegrationResponsibleTel AS IntegrationResponsibleTel,
    tbr.IntegrationResult AS IntegrationResult,
    tbr.IntegrationStatusOther AS IntegrationStatusOther,
    tbr.IntegrationStrategic AS IntegrationStrategic,
    tbr.IntegrationTambonId AS IntegrationTambonId,
    tbr.IntegrationTarget AS IntegrationTarget,
    tbr.IntegrationUnderProvinceId AS IntegrationUnderProvinceId,
    tbr.IntegrationUnitResponsible AS IntegrationUnitResponsible,
    tbr.IsDeleted AS IsDeleted,
    tbr.ItNewAmount AS ItNewAmount,
    tbr.ItNewPricePerAmount AS ItNewPricePerAmount,
    tbr.ItNewTotal AS ItNewTotal,
    tbr.ItNewUnit AS ItNewUnit,
    tbr.ItReasonItemTypeId AS ItReasonItemTypeId,
    tbr.LandAmount AS LandAmount,
    tbr.LandEnterYear AS LandEnterYear,
    tbr.LandPriceCompany AS LandPriceCompany,
    tbr.LandPriceCurrent AS LandPriceCurrent,
    tbr.LandPriceUnit AS LandPriceUnit,
    tbr.LandReason AS LandReason,
    tbr.LandRequestBudget AS LandRequestBudget,
    tbr.LandRequestBudgetPerItem AS LandRequestBudgetPerItem,
    tbr.NationStrategicPlanItemId AS NationStrategicPlanItemId,
    tbr.NeedReason AS NeedReason,
    tbr.NewLandDate AS NewLandDate,
    tbr.NewLandTypeId AS NewLandTypeId,
    tbr.NewPipeLength AS NewPipeLength,
    tbr.NewPipeSize AS NewPipeSize,
    tbr.NewPipeTypeId AS NewPipeTypeId,
    tbr.NewPipeWaterLoss AS NewPipeWaterLoss,
    tbr.OperationAreaText AS OperationAreaText,
    tbr.PastProjectId AS PastProjectId,
    tbr.PlanDay AS PlanDay,
    tbr.Polygon AS Polygon,
    tbr.PowerReserve AS PowerReserve,
    tbr.PowerReserveContentSummary AS PowerReserveContentSummary,
    tbr.PowerReserveEffect AS PowerReserveEffect,
    tbr.PowerReserveInstallDateTime AS PowerReserveInstallDateTime,
    tbr.PowerReserveNumber AS PowerReserveNumber,
    tbr.PowerReserveReason AS PowerReserveReason,
    tbr.PowerReserveResultOutcome AS PowerReserveResultOutcome,
    tbr.PriceReserve AS PriceReserve,
    tbr.PriceReserveGoods AS PriceReserveGoods,
    tbr.ProjectBoq1Date AS ProjectBoq1Date,
    tbr.ProjectBoq2Date AS ProjectBoq2Date,
    tbr.ProjectBoqTypeId AS ProjectBoqTypeId,
    tbr.ProjectDurationTypeId AS ProjectDurationTypeId,
    tbr.ProjectEndDate AS ProjectEndDate,
    tbr.ProjectFormat1Date AS ProjectFormat1Date,
    tbr.ProjectFormat2Date AS ProjectFormat2Date,
    tbr.ProjectFormatTypeId AS ProjectFormatTypeId,
    tbr.ProjectId AS ProjectId,
    tbr.ProjectJobAsset AS ProjectJobAsset,
    tbr.ProjectJobTypeId AS ProjectJobTypeId,
    tbr.ProjectLimit1M1Date AS ProjectLimit1M1Date,
    tbr.ProjectLimit1M2Date AS ProjectLimit1M2Date,
    tbr.ProjectName AS ProjectName,
    tbr.ProjectShortName AS ProjectShortName,
    tbr.ProjectStartDate AS ProjectStartDate,
    tbr.ProjectTor1Date AS ProjectTor1Date,
    tbr.ProjectTor2Date AS ProjectTor2Date,
    tbr.ProjectTorTypeId AS ProjectTorTypeId,
    tbr.ProjectWater1Date AS ProjectWater1Date,
    tbr.ProjectWater2Date AS ProjectWater2Date,
    tbr.ProjectWaterTypeId AS ProjectWaterTypeId,
    tbr.ReserveOfUrgent AS ReserveOfUrgent,
    tbr.ReserveOfUrgentContentSummary AS ReserveOfUrgentContentSummary,
    tbr.ReserveOfUrgentDrought AS ReserveOfUrgentDrought,
    tbr.ReserveOfUrgentEffect AS ReserveOfUrgentEffect,
    tbr.ReserveOfUrgentNumber AS ReserveOfUrgentNumber,
    tbr.ReserveOfUrgentPipe AS ReserveOfUrgentPipe,
    tbr.ReserveOfUrgentPipelength AS ReserveOfUrgentPipelength,
    tbr.ReserveOfUrgentReason AS ReserveOfUrgentReason,
    tbr.ReserveOfUrgentResultOutcome AS ReserveOfUrgentResultOutcome,
    tbr.ReserveOfUrgentTypeId AS ReserveOfUrgentTypeId,
    tbr.ResponsibleAmphoeId AS ResponsibleAmphoeId,
    tbr.ResponsibleEmail AS ResponsibleEmail,
    tbr.ResponsibleName AS ResponsibleName,
    tbr.ResponsiblePosition AS ResponsiblePosition,
    tbr.ResponsibleProvinceId AS ResponsibleProvinceId,
    tbr.ResponsibleTambonId AS ResponsibleTambonId,
    tbr.ResponsibleTel AS ResponsibleTel,
    tbr.ResponsibleUnitId AS ResponsibleUnitId,
    tbr.ResponsibleUnitText AS ResponsibleUnitText,
    tbr.RoiPipeDiameter AS RoiPipeDiameter,
    tbr.RoiPipeLength AS RoiPipeLength,
    tbr.RoiPipeTotalLength AS RoiPipeTotalLength,
    tbr.RoiPipeType AS RoiPipeType,
    tbr.Score AS Score,
    tbr.StartLocation AS StartLocation,
    tbr.StartPaymentYear AS StartPaymentYear,
    tbr.StrategicIndicator AS StrategicIndicator,
    tbr.StrategicIndicatorKPI AS StrategicIndicatorKPI,
    tbr.StrategicObjective AS StrategicObjective,
    tbr.StrategicOutput AS StrategicOutput,
    tbr.StrategicPlanItemId AS StrategicPlanItemId,
    tbr.StrategicResourceEmployee AS StrategicResourceEmployee,
    tbr.StrategicResourceEquipment AS StrategicResourceEquipment,
    tbr.StrategicResourceTech AS StrategicResourceTech,
    tbr.StrategicResult AS StrategicResult,
    tbr.UseLandDate AS UseLandDate,
    tbr.UseLandTypeId AS UseLandTypeId,
    tbr.WaterOther AS WaterOther,
    tbr.hasExistLand AS hasExistLand,
    tbr.hasNewLand AS hasNewLand,
    tbr.hasUseLand AS hasUseLand,
    tbr.waterProblem AS waterProblem,
    tbr.waterProblemConform AS waterProblemConform,
    tbr.waterProjectDetail AS waterProjectDetail,
    tbr.OperationBudgetRequestId AS OperationBudgetRequestId,
    tbr.BudgetDroughtGLCodeId AS BudgetDroughtGLCodeId,
    tbr.DisburseStatusId AS DisburseStatusId,
    tbr.PricePerUnit AS PricePerUnit,
    tbr.ProcessingTimeDays AS ProcessingTimeDays,
    tbr.ReferDocumentId AS ReferDocumentId,
    tbr.Remark AS Remark,
    tbr.RequestName AS RequestName,
    tbr.SupportingDocumentId AS SupportingDocumentId,
    tbr.UnitAmount AS UnitAmount,
    tbr.InvestBudgetRequestId AS InvestBudgetRequestId,
    tbr.SapStatusId AS SapStatusId,
    tbr.BudgetRequestTypeId AS BudgetRequestTypeId,
    tbr.BudgetRequestStatusId AS BudgetRequestStatusId,
    tbr.WholeInvestBudgetRequested AS WholeInvestBudgetRequested,
    tbr.River AS River,
    tbr.ReferenceNumber AS ReferenceNumber,
    tbr.StrategicPlanItemInWorkId AS StrategicPlanItemInWorkId,
    tbr.LinkDocument AS LinkDocument,
    tbr.ReferenceDate AS ReferenceDate,
    tbr.ReferenceNote AS ReferenceNote,
    tbr.NewLandWaitDate AS NewLandWaitDate,
    tbr.ProjectPipe1Date AS ProjectPipe1Date,
    tbr.ProjectPipe2Date AS ProjectPipe2Date,
    tbr.ProjectPipeTypeId AS ProjectPipeTypeId,
    tbr.UseLandWaitDate AS UseLandWaitDate,
    tbr.KPIUnit AS KPIUnit,
    tbr.ProjectKPI AS ProjectKPI,
    tbr.TargetName AS TargetName,
    tbr.TargetUnit AS TargetUnit,
    tbr.BudgetRequestedExtended AS BudgetRequestedExtended,
    tbr.WholeInvestBudgetRequestedExtended AS WholeInvestBudgetRequestedExtended,
    tbr.DurableGoodsNewId AS DurableGoodsNewId,
    tbr.ProjectNameForRename AS ProjectNameForRename,
    tbr.ChangeBudgetYearlyType AS ChangeBudgetYearlyType,
    tbr.ProjectTypeId AS ProjectTypeId,
    tbr.ProvincialAllocationState AS ProvincialAllocationState,
    tbr.TreasuryAmountDetail AS TreasuryAmountDetail,
    tbr.ApprovedWholeInvestBudgetRequested AS ApprovedWholeInvestBudgetRequested,
    tbr.BudgetByProvincialDistrict AS BudgetByProvincialDistrict,
    tbr.BudgetByProvincialViceGovernor AS BudgetByProvincialViceGovernor,
    tbr.LandAmountField AS LandAmountField,
    tbr.LandAmountMeter AS LandAmountMeter,
    tbr.LandAmountWa AS LandAmountWa,
    tbr.LandAmountWork AS LandAmountWork,
    tbr.LeasingTypeId AS LeasingTypeId,
    tbr.ActivityTypeCustomId AS ActivityTypeCustomId,
    tbr.FirstYearBudgetRequested AS FirstYearBudgetRequested,
    tbr.SecondYearBudgetRequested AS SecondYearBudgetRequested,
    tbr.ThirdYearBudgetRequested AS ThirdYearBudgetRequested,
    tbr.ReferenceUploadId AS ReferenceUploadId,
    tbr.CostCenterId AS CostCenterId,
    tbr.ReferenceUploadCode AS ReferenceUploadCode,
    tbr.DurableCategoryCode AS DurableCategoryCode,
    tbr.SapUnitId AS SapUnitId,
    tpj.ProjectId AS tbProject_ProjectId,
    ----------------------------------------------------------
    CASE
        WHEN dup_cnt > 1 THEN dup_cnt
        ELSE 0
    END AS DuplicatedCount,
    CASE 
		WHEN is_date_match_manual then 'DM'
		WHEN is_reprocess and not is_date_match_manual then 'RE'
		else 'NA'
	END as RecordStatus
FROM tbr -- Edit
LEFT JOIN tpj ON (tbr.ProjectId = tpj.ProjectId AND tpj.rn = 1) -- Edit
WHERE tbr.rn = 1 -- Edit
AND (tbr.is_reprocess OR tbr.is_date_match_manual OR tbr.is_date_match_schedule) -- Edit
"""

def get_tbBudgetRequest_staging_schema():
    return [
        {'name': 'BudgetRequestId', 'type': 'INT'},
        {'name': 'CreatedDate', 'type': 'TIMESTAMP'},
        {'name': 'CreatedBy', 'type': 'STRING'},
        {'name': 'UpdatedDate', 'type': 'TIMESTAMP'},
        {'name': 'UpdatedBy', 'type': 'STRING'},
        {'name': 'BudgetYearNo', 'type': 'INT'},
        {'name': 'BudgetRequested', 'type': 'FLOAT'},
        {'name': 'RequesterUnit', 'type': 'INT'},
        {'name': 'Position', 'type': 'STRING'},
        {'name': 'BudgetRequestYearlyTypeId', 'type': 'INT'},
        {'name': 'EntityStatusId', 'type': 'INT'},
        {'name': 'BeginPeriodCustomerAmount', 'type': 'FLOAT'},
        {'name': 'IncreaseCustomerAmount', 'type': 'FLOAT'},
        {'name': 'DecreaseCustomerAmount', 'type': 'FLOAT'},
        {'name': 'WaterSoldQty', 'type': 'FLOAT'},
        {'name': 'WaterProducedQty', 'type': 'FLOAT'},
        {'name': 'WaterProductionQty', 'type': 'FLOAT'},
        {'name': 'ImageId', 'type': 'INT'},
        {'name': 'ApprovedDate', 'type': 'TIMESTAMP'},
        {'name': 'ApprovedUserId', 'type': 'INT'},
        {'name': 'ApprovedBudgetAmount', 'type': 'FLOAT'},
        {'name': 'RequestId', 'type': 'INT'},
        {'name': 'AllocatedBudgetAmount', 'type': 'FLOAT'},
        {'name': 'BudgetRequestNumber', 'type': 'STRING'},
        {'name': 'TrusteeUnitId', 'type': 'INT'},
        {'name': 'ActivityTypeId', 'type': 'INT'},
        {'name': 'AddWaterProd', 'type': 'FLOAT'},
        {'name': 'AddWaterUserAmount', 'type': 'INT'},
        {'name': 'AmountOfWaterIncrease', 'type': 'STRING'},
        {'name': 'AnalyzeBC', 'type': 'FLOAT'},
        {'name': 'AnalyzeIRR', 'type': 'FLOAT'},
        {'name': 'AnalyzeNPV', 'type': 'FLOAT'},
        {'name': 'CoordinatorEmail', 'type': 'STRING'},
        {'name': 'CoordinatorName', 'type': 'STRING'},
        {'name': 'CoordinatorPosition', 'type': 'STRING'},
        {'name': 'CoordinatorTel', 'type': 'STRING'},
        {'name': 'Discriminator', 'type': 'STRING'},
        {'name': 'DurableGoodsId', 'type': 'INT'},
        {'name': 'EndLocation', 'type': 'STRING'},
        {'name': 'EndPaymentYear', 'type': 'INT'},
        {'name': 'ExistPipeRepairAmount', 'type': 'INT'},
        {'name': 'ExistPipeSize', 'type': 'FLOAT'},
        {'name': 'ExistPipeTypeId', 'type': 'INT'},
        {'name': 'ExistPipeWaterLoss', 'type': 'FLOAT'},
        {'name': 'ExistPipeYear', 'type': 'INT'},
        {'name': 'ExistWaterProd', 'type': 'FLOAT'},
        {'name': 'ExistWaterUserAmount', 'type': 'INT'},
        {'name': 'GoodsNewAmount', 'type': 'INT'},
        {'name': 'GoodsNewPricePerAmount', 'type': 'FLOAT'},
        {'name': 'GoodsNewTotal', 'type': 'FLOAT'},
        {'name': 'GoodsNewUnit', 'type': 'STRING'},
        {'name': 'GoodsReasonItemTypeId', 'type': 'INT'},
        {'name': 'HasProjectLimit1M1', 'type': 'BOOLEAN'},
        {'name': 'HasProjectLimit1M2', 'type': 'BOOLEAN'},
        {'name': 'InstallMeterAmount', 'type': 'INT'},
        {'name': 'InstallMeterSize', 'type': 'INT'},
        {'name': 'InstallMeterTypeId', 'type': 'INT'},
        {'name': 'InstallMeterWaterLoss', 'type': 'FLOAT'},
        {'name': 'IntegrationAmphoeId', 'type': 'INT'},
        {'name': 'IntegrationAreaText', 'type': 'STRING'},
        {'name': 'IntegrationBenefit', 'type': 'STRING'},
        {'name': 'IntegrationCoordinatorEmail', 'type': 'STRING'},
        {'name': 'IntegrationCoordinatorName', 'type': 'STRING'},
        {'name': 'IntegrationCoordinatorPosition', 'type': 'STRING'},
        {'name': 'IntegrationCoordinatorTel', 'type': 'STRING'},
        {'name': 'IntegrationEvaDuration', 'type': 'STRING'},
        {'name': 'IntegrationEvaEquipment', 'type': 'STRING'},
        {'name': 'IntegrationEvaImplement', 'type': 'STRING'},
        {'name': 'IntegrationGuideline', 'type': 'STRING'},
        {'name': 'IntegrationIndicator', 'type': 'STRING'},
        {'name': 'IntegrationIsPresident', 'type': 'BOOLEAN'},
        {'name': 'IntegrationIsResolution', 'type': 'BOOLEAN'},
        {'name': 'IntegrationIsStatusOther', 'type': 'BOOLEAN'},
        {'name': 'IntegrationIsUnderProvince', 'type': 'BOOLEAN'},
        {'name': 'IntegrationObjective', 'type': 'STRING'},
        {'name': 'IntegrationOperation', 'type': 'STRING'},
        {'name': 'IntegrationOutput', 'type': 'STRING'},
        {'name': 'IntegrationPlanId', 'type': 'INT'},
        {'name': 'IntegrationPolicy', 'type': 'STRING'},
        {'name': 'IntegrationPosition', 'type': 'STRING'},
        {'name': 'IntegrationPresidentDate', 'type': 'TIMESTAMP'},
        {'name': 'IntegrationProjectTypeId', 'type': 'INT'},
        {'name': 'IntegrationProvinceId', 'type': 'INT'},
        {'name': 'IntegrationQualitative', 'type': 'STRING'},
        {'name': 'IntegrationQuantitative', 'type': 'STRING'},
        {'name': 'IntegrationReason', 'type': 'STRING'},
        {'name': 'IntegrationRef', 'type': 'STRING'},
        {'name': 'IntegrationResolutionDate', 'type': 'TIMESTAMP'},
        {'name': 'IntegrationResponsibleEmail', 'type': 'STRING'},
        {'name': 'IntegrationResponsibleName', 'type': 'STRING'},
        {'name': 'IntegrationResponsiblePosition', 'type': 'STRING'},
        {'name': 'IntegrationResponsibleTel', 'type': 'STRING'},
        {'name': 'IntegrationResult', 'type': 'STRING'},
        {'name': 'IntegrationStatusOther', 'type': 'STRING'},
        {'name': 'IntegrationStrategic', 'type': 'STRING'},
        {'name': 'IntegrationTambonId', 'type': 'INT'},
        {'name': 'IntegrationTarget', 'type': 'STRING'},
        {'name': 'IntegrationUnderProvinceId', 'type': 'INT'},
        {'name': 'IntegrationUnitResponsible', 'type': 'STRING'},
        {'name': 'IsDeleted', 'type': 'BOOLEAN'},
        {'name': 'ItNewAmount', 'type': 'INT'},
        {'name': 'ItNewPricePerAmount', 'type': 'FLOAT'},
        {'name': 'ItNewTotal', 'type': 'FLOAT'},
        {'name': 'ItNewUnit', 'type': 'STRING'},
        {'name': 'ItReasonItemTypeId', 'type': 'INT'},
        {'name': 'LandAmount', 'type': 'FLOAT'},
        {'name': 'LandEnterYear', 'type': 'INT'},
        {'name': 'LandPriceCompany', 'type': 'FLOAT'},
        {'name': 'LandPriceCurrent', 'type': 'FLOAT'},
        {'name': 'LandPriceUnit', 'type': 'FLOAT'},
        {'name': 'LandReason', 'type': 'STRING'},
        {'name': 'LandRequestBudget', 'type': 'FLOAT'},
        {'name': 'LandRequestBudgetPerItem', 'type': 'FLOAT'},
        {'name': 'NationStrategicPlanItemId', 'type': 'INT'},
        {'name': 'NeedReason', 'type': 'STRING'},
        {'name': 'NewLandDate', 'type': 'TIMESTAMP'},
        {'name': 'NewLandTypeId', 'type': 'INT'},
        {'name': 'NewPipeLength', 'type': 'FLOAT'},
        {'name': 'NewPipeSize', 'type': 'FLOAT'},
        {'name': 'NewPipeTypeId', 'type': 'INT'},
        {'name': 'NewPipeWaterLoss', 'type': 'FLOAT'},
        {'name': 'OperationAreaText', 'type': 'STRING'},
        {'name': 'PastProjectId', 'type': 'INT'},
        {'name': 'PlanDay', 'type': 'INT'},
        {'name': 'Polygon', 'type': 'STRING'},
        {'name': 'PowerReserve', 'type': 'FLOAT'},
        {'name': 'PowerReserveContentSummary', 'type': 'STRING'},
        {'name': 'PowerReserveEffect', 'type': 'STRING'},
        {'name': 'PowerReserveInstallDateTime', 'type': 'TIMESTAMP'},
        {'name': 'PowerReserveNumber', 'type': 'STRING'},
        {'name': 'PowerReserveReason', 'type': 'STRING'},
        {'name': 'PowerReserveResultOutcome', 'type': 'STRING'},
        {'name': 'PriceReserve', 'type': 'FLOAT'},
        {'name': 'PriceReserveGoods', 'type': 'FLOAT'},
        {'name': 'ProjectBoq1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectBoq2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectBoqTypeId', 'type': 'INT'},
        {'name': 'ProjectDurationTypeId', 'type': 'INT'},
        {'name': 'ProjectEndDate', 'type': 'TIMESTAMP'},
        {'name': 'ProjectFormat1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectFormat2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectFormatTypeId', 'type': 'INT'},
        {'name': 'ProjectId', 'type': 'INT'},
        {'name': 'ProjectJobAsset', 'type': 'STRING'},
        {'name': 'ProjectJobTypeId', 'type': 'INT'},
        {'name': 'ProjectLimit1M1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectLimit1M2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectName', 'type': 'STRING'},
        {'name': 'ProjectShortName', 'type': 'STRING'},
        {'name': 'ProjectStartDate', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTor1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTor2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectTorTypeId', 'type': 'INT'},
        {'name': 'ProjectWater1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectWater2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectWaterTypeId', 'type': 'INT'},
        {'name': 'ReserveOfUrgent', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentContentSummary', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentDrought', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentEffect', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentNumber', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentPipe', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentPipelength', 'type': 'FLOAT'},
        {'name': 'ReserveOfUrgentReason', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentResultOutcome', 'type': 'STRING'},
        {'name': 'ReserveOfUrgentTypeId', 'type': 'INT'},
        {'name': 'ResponsibleAmphoeId', 'type': 'INT'},
        {'name': 'ResponsibleEmail', 'type': 'STRING'},
        {'name': 'ResponsibleName', 'type': 'STRING'},
        {'name': 'ResponsiblePosition', 'type': 'STRING'},
        {'name': 'ResponsibleProvinceId', 'type': 'INT'},
        {'name': 'ResponsibleTambonId', 'type': 'INT'},
        {'name': 'ResponsibleTel', 'type': 'STRING'},
        {'name': 'ResponsibleUnitId', 'type': 'INT'},
        {'name': 'ResponsibleUnitText', 'type': 'STRING'},
        {'name': 'RoiPipeDiameter', 'type': 'FLOAT'},
        {'name': 'RoiPipeLength', 'type': 'FLOAT'},
        {'name': 'RoiPipeTotalLength', 'type': 'FLOAT'},
        {'name': 'RoiPipeType', 'type': 'STRING'},
        {'name': 'Score', 'type': 'FLOAT'},
        {'name': 'StartLocation', 'type': 'STRING'},
        {'name': 'StartPaymentYear', 'type': 'INT'},
        {'name': 'StrategicIndicator', 'type': 'STRING'},
        {'name': 'StrategicIndicatorKPI', 'type': 'STRING'},
        {'name': 'StrategicObjective', 'type': 'STRING'},
        {'name': 'StrategicOutput', 'type': 'STRING'},
        {'name': 'StrategicPlanItemId', 'type': 'INT'},
        {'name': 'StrategicResourceEmployee', 'type': 'STRING'},
        {'name': 'StrategicResourceEquipment', 'type': 'STRING'},
        {'name': 'StrategicResourceTech', 'type': 'STRING'},
        {'name': 'StrategicResult', 'type': 'STRING'},
        {'name': 'UseLandDate', 'type': 'TIMESTAMP'},
        {'name': 'UseLandTypeId', 'type': 'INT'},
        {'name': 'WaterOther', 'type': 'STRING'},
        {'name': 'hasExistLand', 'type': 'BOOLEAN'},
        {'name': 'hasNewLand', 'type': 'BOOLEAN'},
        {'name': 'hasUseLand', 'type': 'BOOLEAN'},
        {'name': 'waterProblem', 'type': 'STRING'},
        {'name': 'waterProblemConform', 'type': 'BOOLEAN'},
        {'name': 'waterProjectDetail', 'type': 'STRING'},
        {'name': 'OperationBudgetRequestId', 'type': 'INT'},
        {'name': 'BudgetDroughtGLCodeId', 'type': 'INT'},
        {'name': 'DisburseStatusId', 'type': 'INT'},
        {'name': 'PricePerUnit', 'type': 'FLOAT'},
        {'name': 'ProcessingTimeDays', 'type': 'INT'},
        {'name': 'ReferDocumentId', 'type': 'INT'},
        {'name': 'Remark', 'type': 'STRING'},
        {'name': 'RequestName', 'type': 'STRING'},
        {'name': 'SupportingDocumentId', 'type': 'INT'},
        {'name': 'UnitAmount', 'type': 'FLOAT'},
        {'name': 'InvestBudgetRequestId', 'type': 'INT'},
        {'name': 'SapStatusId', 'type': 'INT'},
        {'name': 'BudgetRequestTypeId', 'type': 'INT'},
        {'name': 'BudgetRequestStatusId', 'type': 'INT'},
        {'name': 'WholeInvestBudgetRequested', 'type': 'FLOAT'},
        {'name': 'River', 'type': 'STRING'},
        {'name': 'ReferenceNumber', 'type': 'STRING'},
        {'name': 'StrategicPlanItemInWorkId', 'type': 'INT'},
        {'name': 'LinkDocument', 'type': 'STRING'},
        {'name': 'ReferenceDate', 'type': 'TIMESTAMP'},
        {'name': 'ReferenceNote', 'type': 'STRING'},
        {'name': 'NewLandWaitDate', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipe1Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipe2Date', 'type': 'TIMESTAMP'},
        {'name': 'ProjectPipeTypeId', 'type': 'INT'},
        {'name': 'UseLandWaitDate', 'type': 'TIMESTAMP'},
        {'name': 'KPIUnit', 'type': 'STRING'},
        {'name': 'ProjectKPI', 'type': 'STRING'},
        {'name': 'TargetName', 'type': 'STRING'},
        {'name': 'TargetUnit', 'type': 'STRING'},
        {'name': 'BudgetRequestedExtended', 'type': 'FLOAT'},
        {'name': 'WholeInvestBudgetRequestedExtended', 'type': 'FLOAT'},
        {'name': 'DurableGoodsNewId', 'type': 'INT'},
        {'name': 'ProjectNameForRename', 'type': 'STRING'},
        {'name': 'ChangeBudgetYearlyType', 'type': 'BOOLEAN'},
        {'name': 'ProjectTypeId', 'type': 'INT'},
        {'name': 'ProvincialAllocationState', 'type': 'INT'},
        {'name': 'TreasuryAmountDetail', 'type': 'STRING'},
        {'name': 'ApprovedWholeInvestBudgetRequested', 'type': 'FLOAT'},
        {'name': 'BudgetByProvincialDistrict', 'type': 'FLOAT'},
        {'name': 'BudgetByProvincialViceGovernor', 'type': 'FLOAT'},
        {'name': 'LandAmountField', 'type': 'FLOAT'},
        {'name': 'LandAmountMeter', 'type': 'FLOAT'},
        {'name': 'LandAmountWa', 'type': 'FLOAT'},
        {'name': 'LandAmountWork', 'type': 'FLOAT'},
        {'name': 'LeasingTypeId', 'type': 'INT'},
        {'name': 'ActivityTypeCustomId', 'type': 'INT'},
        {'name': 'FirstYearBudgetRequested', 'type': 'FLOAT'},
        {'name': 'SecondYearBudgetRequested', 'type': 'FLOAT'},
        {'name': 'ThirdYearBudgetRequested', 'type': 'FLOAT'},
        {'name': 'ReferenceUploadId', 'type': 'STRING'},
        {'name': 'CostCenterId', 'type': 'INT'},
        {'name': 'ReferenceUploadCode', 'type': 'STRING'},
        {'name': 'DurableCategoryCode', 'type': 'STRING'},
        {'name': 'SapUnitId', 'type': 'INT'},
        {'name': 'tbProject_ProjectId', 'type': 'INT'},
        {'name': 'DuplicatedCount', 'type': 'INT'},
        {'name': 'RecordStatus', 'type': 'STRING'},
    ]
    
